name: quick_mark
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  introduction_screen: ^3.1.17
  http: ^1.2.0
  mobile_scanner: ^5.0.0
  google_mlkit_face_detection: ^0.10.0
  image: ^4.1.7
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  crypto: ^3.0.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/